### PR TITLE
AD Group Managed Service Accounts

### PR DESCRIPTION
**Pull request by gbiellem**
Related to #93

Currenlty NSB host doesn't support AD Group Management Accounts. Group Managed Service accounts allow the provisioning of service accounts without knowing the service account passwords. Windows manages the password and periodically handles the password change,

To allow the NSB host to use the GMSA accounts the installation doesn't assume a password has be supplied for a user.

### CODE REVIEW

**Comment by andreasohlund** [comment]
Seems like the host32 project fails to build?

**Comment by gbiellem** [comment]
Looks like some guy called @andreasohlund broke the release branch which is why this PR is failing - https://builds.particular.net/viewType.html?buildTypeId=NServiceBus_NServiceBusHost_1Build&branch_NServiceBus_NServiceBusHost=release-7.0.0&tab=buildTypeStatusDiv

I can look at it tomorrow if you're busy

**Comment by andreasohlund** [comment]
ha, I know that guy, will twist his arm to fix it!

**Comment by andreasohlund** [comment]
Should be fixed now :)

**Comment by andreasohlund** [comment]
LGTM

@Particular/nservicebus-maintainers please review

**Comment by bording** [comment]
Looks like a simple enough change, even if this is a bit of a hack: https://github.com/Particular/Topshelf/commit/5c676cdde9f82b920e4bb6e5d941fcf5bc828c4b

Out of curiosity, what changes did we need that required us to fork of Topshelf instead of keeping up to date with the main release?

**Comment by andreasohlund** [comment]
>Out of curiosity, what changes did we need that required us to fork of Topshelf instead of keeping up to date with the main release?

Think we just fell behind and then we needed to quickly fix the log4net ref (when they screwed up and changed their public key)

**Comment by andreasohlund** [comment]
@gbiellem is there some doco we need to update?

**Pull request merged**
