### PR TITLE
[WIP] Upgrade host to NServiceBus v6

### PR DESCRIPTION
**Pull request by danielmarbach**
Relates to #41 

This makes the develop branch V6 ready and also completes some of the work started with https://github.com/Particular/NServiceBus.Host/pull/32

* [X] `IConfigureThisEndpoint`, `EndpointSLAAttribute` and `EndpointNameAttribute` are now part of the hosts and on the root `NServiceBus` namespace
* [X] Source package hack includes `IConfigureThisEndpoint` to be able to compile and excludes it in the nspec. 
* [x] Verify that the `IConfigureThisEndpoint` hack for Source package actually works
* [ ] Deprecate or move out WcfIntegration depending on outcome of https://github.com/Particular/FeatureDevelopment/issues/362
* [ ] Fix [`LiteProfileHandler`](https://github.com/Particular/NServiceBus.Host/compare/UpgradeHostV6?expand=1#diff-67d15a42e88874f016b2e44bb70f2fc9R15) by hooking into the pipeline and potentially replace the standard `MoveFaultsToErrorQueue` behavior with a discarding one
* [x] Update the doco snippets for v6 to renable https://github.com/Particular/docs.particular.net/commit/36fb4ddc338ddcacb8c3d1ec32f7475eac1670e1

@Particular/engineers thoughts how to move this forward?

### CODE REVIEW

**Comment by danielmarbach** [comment]
@SimonCropp See the commit reference for the doco snippets

**Comment by danielmarbach** [comment]
Fixed the doco issue by using the PR packages temporarily

**Comment by SzymonPobiega** [comment]
With regards to `LiteProfileHandler`, what is the reason to actually drop these messages? We're creating the error queue anyway as part of `F5` experience so why not just use it?

**Comment by adamralph** [comment]
Is this v6 or v7?

**Comment by danielmarbach** [comment]
@adamralph v6 or v7 of what?

**Comment by adamralph** [comment]
I'm not sure. Everything in the issue refers to v6 but then I see a commit containing 7.0 and a milestone of 7.0.0.

Is it NServiceBus 6.0 but NServiceBus.Host 7.0?

**Comment by SimonCropp** [comment]
> Is it NServiceBus 6.0 but NServiceBus.Host 7.0?

yes

**Comment by SimonCropp** [comment]
merging this to develop since we need from real build numbers to test compat on downstream docs+samples. the currently myget uploaded "pullrequest" nuget cannot be evolved forward
i split out the two remaining items into issues

**Pull request merged**
