### PR TITLE
Assembly scanning changes in core v6

### PR DESCRIPTION
**Pull request by SeanFeldman**
Related to https://github.com/Particular/NServiceBus/pull/2711

Assembly scanning in V6 is going to deprecate `configuration.AssembliesToScan()`

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@Particular/nservicebus please review

**Comment by SeanFeldman** [comment]
Also, what should be the milestone for this one since it will be targeting Core v6?

**Comment by SeanFeldman** [comment]
@SimonCropp I think we are ok to merge this one. Any objections?

**Comment by SimonCropp** [comment]
looks ok

> Also, what should be the milestone for this one since it will be targeting Core v6?

seems there is no breaking changes yet so this would be  a patch milestone

**Comment by SeanFeldman** [comment]
Originally was planned for core v6, but you're correct, it could be released earlier as a patch.
A 6.0.1 patch then?

**Comment by SimonCropp** [comment]
i think hold off until the v6 core version. there is no point deploying before then

But it might be possible to release ( v6 core version) of the host with no breaking changes to the host API in which case it would still be  6.0.1

**Comment by SeanFeldman** [comment]
I'll hold off. The change is not that significant anyways.

There's a possibility that we'll need some more changes to accommodate https://github.com/Particular/Requirements/issues/255

**Comment by SeanFeldman** [comment]
Should this be merged into `develop` with core `develop` being v6 @SimonCropp ?

**Comment by SimonCropp** [comment]
@SeanFeldman i am happy with develop in the host being switch over to v6 of the core

**Pull request merged**
