### PR TITLE
Support GMSA Accounts

### PR DESCRIPTION
**Pull request by gbiellem**
Related to #93

Currenlty NSB host doesn't support AD Group Management Accounts.  Group Managed Service accounts allow the provisioning of service accounts without knowing the service account passwords.  Windows manages the password and periodically handles the password change,

To allow the NSB host to use the GMSA accounts the installation doesn't assume a password has be supplied for a user.

### CODE REVIEW

**Comment by andreasohlund** [comment]
@gbiellem seems like the nunit v3 component test fails? (can't find the test asm)

**Comment by gbiellem** [comment]
yep looks like master wasn't updated to NUnit 3 but the build was. Do you want that added to this PR?

**Comment by andreasohlund** [comment]
Probably better to separate?

**Comment by gbiellem** [comment]
@andreasohlund actually NUnit3 isn't the issue.  This PR is based off master which doesn't have the  component tests project at all. In fact master hasn't been touched in over a year.  Develop has moved on and is now NSB v6.  How do you want to proceed?

**Comment by gbiellem** [comment]
@andreasohlund actually NUnit3 isn't the issue. This PR is based off master which doesn't have the component tests project at all.  How do you want to proceed?

**Comment by andreasohlund** [comment]
How about we target the upcoming release with this instead? (ie retarget the PR towards the release branch?)

**Comment by gbiellem** [comment]
OK  I'll kill off this PR and raise a new one against the release branch

**Pull request closed without merging**
